name: Build Stealth Frida Windows-x64
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout PhantomFrida
        uses: actions/checkout@v4
        with:
          repository: TheQmaks/phantom-frida
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          choco install visualstudio2022buildtools git nodejs nasm 7zip -y
          refreshenv
      - name: Build Stealth Frida
        run: |
          python build.py --version 17.2.0 --name system --port 35791 --arch windows-x64 --extended --verify
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stealth-frida-windows-x64
          path: output/
